/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ChatbotEntryId = IDL.Nat;
export const ChatbotEntry = IDL.Record({
  'id' : ChatbotEntryId,
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const ReviewId = IDL.Nat;
export const BookId = IDL.Nat;
export const Review = IDL.Record({
  'id' : ReviewId,
  'reviewDate' : IDL.Text,
  'bookId' : BookId,
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPostId = IDL.Nat;
export const BlogPost = IDL.Record({
  'id' : BlogPostId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedDate' : IDL.Text,
  'published' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'readTime' : IDL.Nat,
  'excerpt' : IDL.Text,
});
export const Book = IDL.Record({
  'id' : BookId,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'amazonEbookLink' : IDL.Text,
  'amazonPaperbackLink' : IDL.Text,
  'publishedDate' : IDL.Text,
  'lookInsideText' : IDL.Text,
  'authorNotes' : IDL.Text,
  'description' : IDL.Text,
  'genres' : IDL.Vec(IDL.Text),
  'coverUrl' : IDL.Text,
  'formats' : IDL.Vec(IDL.Text),
  'subtitle' : IDL.Text,
});
export const ContactId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : ContactId,
  'inquiryType' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Subscriber = IDL.Record({
  'subscribedAt' : IDL.Text,
  'email' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatbotEntry' : IDL.Func([ChatbotEntry], [ChatbotEntryId], []),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'resetAdminPasswordToDefault' : IDL.Func([], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'addReview' : IDL.Func([Review], [ReviewId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func([BlogPost], [BlogPostId], []),
  'createBook' : IDL.Func([Book], [BookId], []),
  'deleteBlogPost' : IDL.Func([BlogPostId], [], []),
  'deleteBook' : IDL.Func([BookId], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllChatbotEntries' : IDL.Func([], [IDL.Vec(ChatbotEntry)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllPageVisits' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
  'getBlogPost' : IDL.Func([BlogPostId], [BlogPost], ['query']),
  'getBook' : IDL.Func([BookId], [Book], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPageVisits' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getRelatedBooks' : IDL.Func([BookId], [IDL.Vec(Book)], ['query']),
  'getReviewsForBook' : IDL.Func([BookId], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPageVisit' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedInitialData' : IDL.Func([], [], []),
  'submitContactForm' : IDL.Func([ContactSubmission], [ContactId], []),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
  'updateBlogPost' : IDL.Func([BlogPostId, BlogPost], [], []),
  'updateBook' : IDL.Func([BookId, Book], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ChatbotEntryId = IDL.Nat;
  const ChatbotEntry = IDL.Record({
    'id' : ChatbotEntryId,
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const ReviewId = IDL.Nat;
  const BookId = IDL.Nat;
  const Review = IDL.Record({
    'id' : ReviewId,
    'reviewDate' : IDL.Text,
    'bookId' : BookId,
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPostId = IDL.Nat;
  const BlogPost = IDL.Record({
    'id' : BlogPostId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedDate' : IDL.Text,
    'published' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'readTime' : IDL.Nat,
    'excerpt' : IDL.Text,
  });
  const Book = IDL.Record({
    'id' : BookId,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'amazonEbookLink' : IDL.Text,
  'amazonPaperbackLink' : IDL.Text,
    'publishedDate' : IDL.Text,
    'lookInsideText' : IDL.Text,
    'authorNotes' : IDL.Text,
    'description' : IDL.Text,
    'genres' : IDL.Vec(IDL.Text),
    'coverUrl' : IDL.Text,
    'formats' : IDL.Vec(IDL.Text),
    'subtitle' : IDL.Text,
  });
  const ContactId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : ContactId,
    'inquiryType' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Subscriber = IDL.Record({
    'subscribedAt' : IDL.Text,
    'email' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatbotEntry' : IDL.Func([ChatbotEntry], [ChatbotEntryId], []),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'resetAdminPasswordToDefault' : IDL.Func([], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'addReview' : IDL.Func([Review], [ReviewId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func([BlogPost], [BlogPostId], []),
    'createBook' : IDL.Func([Book], [BookId], []),
    'deleteBlogPost' : IDL.Func([BlogPostId], [], []),
    'deleteBook' : IDL.Func([BookId], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllChatbotEntries' : IDL.Func([], [IDL.Vec(ChatbotEntry)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllPageVisits' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
    'getBlogPost' : IDL.Func([BlogPostId], [BlogPost], ['query']),
    'getBook' : IDL.Func([BookId], [Book], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPageVisits' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getRelatedBooks' : IDL.Func([BookId], [IDL.Vec(Book)], ['query']),
    'getReviewsForBook' : IDL.Func([BookId], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPageVisit' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedInitialData' : IDL.Func([], [], []),
    'submitContactForm' : IDL.Func([ContactSubmission], [ContactId], []),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
    'updateBlogPost' : IDL.Func([BlogPostId, BlogPost], [], []),
    'updateBook' : IDL.Func([BookId, Book], [], []),
  });
};

export const init = ({ IDL }) => { return []; };