/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : BlogPostId,
  'title' : string,
  'content' : string,
  'publishedDate' : string,
  'published' : boolean,
  'tags' : Array<string>,
  'readTime' : bigint,
  'excerpt' : string,
}
export type BlogPostId = bigint;
export interface Book {
  'id' : BookId,
  'title' : string,
  'featured' : boolean,
  'amazonEbookLink' : string,
  'amazonPaperbackLink' : string,
  'publishedDate' : string,
  'lookInsideText' : string,
  'authorNotes' : string,
  'description' : string,
  'genres' : Array<string>,
  'coverUrl' : string,
  'formats' : Array<string>,
  'subtitle' : string,
}
export type BookId = bigint;
export interface ChatbotEntry {
  'id' : ChatbotEntryId,
  'question' : string,
  'answer' : string,
}
export type ChatbotEntryId = bigint;
export type ContactId = bigint;
export interface ContactSubmission {
  'id' : ContactId,
  'inquiryType' : string,
  'name' : string,
  'submittedAt' : string,
  'email' : string,
  'message' : string,
}
export interface Review {
  'id' : ReviewId,
  'reviewDate' : string,
  'bookId' : BookId,
  'reviewText' : string,
  'reviewerName' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface Subscriber { 'subscribedAt' : string, 'email' : string }
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatbotEntry' : ActorMethod<[ChatbotEntry], ChatbotEntryId>,
  'changeAdminPassword' : ActorMethod<[string, string], boolean>,
  'resetAdminPasswordToDefault' : ActorMethod<[], undefined>,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
  'addReview' : ActorMethod<[Review], ReviewId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<[BlogPost], BlogPostId>,
  'createBook' : ActorMethod<[Book], BookId>,
  'deleteBlogPost' : ActorMethod<[BlogPostId], undefined>,
  'deleteBook' : ActorMethod<[BookId], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAllChatbotEntries' : ActorMethod<[], Array<ChatbotEntry>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllPageVisits' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllSubscribers' : ActorMethod<[], Array<Subscriber>>,
  'getBlogPost' : ActorMethod<[BlogPostId], BlogPost>,
  'getBook' : ActorMethod<[BookId], Book>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPageVisits' : ActorMethod<[string], bigint>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getRelatedBooks' : ActorMethod<[BookId], Array<Book>>,
  'getReviewsForBook' : ActorMethod<[BookId], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPageVisit' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedInitialData' : ActorMethod<[], undefined>,
  'submitContactForm' : ActorMethod<[ContactSubmission], ContactId>,
  'subscribeToNewsletter' : ActorMethod<[string], undefined>,
  'updateBlogPost' : ActorMethod<[BlogPostId, BlogPost], undefined>,
  'updateBook' : ActorMethod<[BookId, Book], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];